apiVersion: v1
kind: Service
metadata:
  name: myapp-service-np
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp
    type: frontend

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   labels:
#     app: myapp
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: myapp

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service-lb
#   labels:
#     app: myapp
# spec:
#   type: LoadBalancer
#   ports:
#     - targetPort: 80
#       port: 80
#       nodePort: 30008
#   selector:
#     app: myapp
